version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: imperial
      POSTGRES_PASSWORD: imperial
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  rabbit:
    image: bitnami/rabbitmq
    environment:
      RABBITMQ_USERNAME: imperial
      RABBITMQ_PASSWORD: imperial
    ports:
      - "5672:5672"
      - "15672:15672"
