import {
  TypeScript as TypeScriptIcon,
  HTML as HTMLIcon,
  GraphQL as GraphQLIcon,
  CoffeeScript as CoffeeScriptIcon,
  Handlebars as HandlebarsIcon,
  Clojure as ClojureIcon,
  Docker as DockerIcon,
  Java as JavaIcon,
  JavaScript as JavaScriptIcon,
  CSS as CSSIcon,
  Go as GoIcon,
  Kotlin as KotlinIcon,
  Lua as LuaIcon,
  Swift as SwiftIcon,
  MySQL as MySQLIcon,
  Less as LessIcon,
  FSharp as FSharpIcon,
  ObjectiveC as ObjectiveCIcon,
} from "../components/ui/icons/languages";
import { Language } from "../types";

/* ENV and some static stuff */
export const API_BASE = "http://localhost:80/";
export const API_VERSION_V1 = "v1";
export const FULL_URI_V1 = API_BASE + API_VERSION_V1;

/* Socials */
export const DiscordURL = "https://discord.gg/cTm85eW49D";
export const GitHubURL = "https://github.com/imperialbin";
export const TwitterURL = "https://twitter.com/imperialbin";

/* Supported Languages */
export const supportedLanguages: Array<Language> = [
  { id: 1, name: "apex", extensions: ["cls"] },
  { id: 2, name: "azcli" },
  { id: 3, name: "bat", extensions: ["bat"] },
  { id: 4, name: "c", extensions: ["c", "cats", "h", "idc", "w"] },
  {
    id: 5,
    name: "clojure",
    icon: ClojureIcon,
    extensions: [
      "clj",
      "boot",
      "cl2",
      "cljc",
      "cljs",
      "cljs",
      "cljscm",
      "cljx",
      "hic",
    ],
  },
  {
    id: 6,
    name: "coffeescript",
    icon: CoffeeScriptIcon,
    extensions: ["coffee", "_coffee", "cake", "cjsx", "cson", "iced"],
  },
  {
    id: 7,
    name: "cpp",
    extensions: [
      "cpp",
      "c++",
      "cc",
      "cp",
      "cxx",
      "h",
      "h++",
      "hh",
      "hpp",
      "hxx",
      "inc",
      "inl",
      "ipp",
      "tcc",
      "tpp",
    ],
  },
  { id: 8, name: "csharp", extensions: ["cs", "cake", "cshtml", "csx"] },
  { id: 9, name: "csp" },
  { id: 10, name: "css", icon: CSSIcon, extensions: ["css"] },
  { id: 11, name: "dockerfile", icon: DockerIcon, extensions: ["dockerfile"] },
  {
    id: 12,
    name: "fsharp",
    icon: FSharpIcon,
    extensions: ["fs", "fsi", "fsx"],
  },
  { id: 13, name: "go", icon: GoIcon, extensions: ["go"] },
  { id: 14, name: "graphql", icon: GraphQLIcon, extensions: ["gql"] },
  {
    id: 15,
    name: "handlebars",
    icon: HandlebarsIcon,
    extensions: ["handlebars", "hbs"],
  },
  {
    id: 16,
    name: "html",
    icon: HTMLIcon,
    extensions: ["html", "htm", "inc", "st", "xht", "xhtml"],
  },
  {
    id: 17,
    name: "ini",
    extensions: ["ini", "cfg", "prefs", "pro", "properties"],
  },
  { id: 18, name: "java", icon: JavaIcon, extensions: ["java"] },
  {
    id: 19,
    name: "javascript",
    icon: JavaScriptIcon,
    extensions: ["js", "es", "es6"],
  },
  {
    id: 20,
    name: "json",
    extensions: ["json", "geojson", "lock", "topojson"],
  },
  {
    id: 21,
    name: "kotlin",
    icon: KotlinIcon,
    extensions: ["kt", "ktm", "kts"],
  },
  { id: 22, name: "less", icon: LessIcon, extensions: ["less"] },
  {
    id: 23,
    name: "lua",
    icon: LuaIcon,
    extensions: ["lua", "fcgi", "nse", "pd_lua", "rbxs", "wlua"],
  },
  {
    id: 24,
    name: "markdown",
    extensions: ["md", "markdown", "mkd", "mkdn", "mkdown", "ron"],
  },
  { id: 25, name: "msdax" },
  { id: 26, name: "mysql", icon: MySQLIcon, extensions: ["mysql"] },
  {
    id: 27,
    name: "objective-c",
    icon: ObjectiveCIcon,
    extensions: ["m", "h"],
  },
  {
    id: 28,
    name: "pascal",
    extensions: ["pas", "dfm", "dpr", "inc", "lpr", "pp"],
  },
  { id: 29, name: "perl", extensions: ["pl", "pm", "perl", "plx", "pod"] },
  { id: 30, name: "pgsql", extensions: ["pgsql"] },
  { id: 31, name: "php", extensions: ["php", "php3", "php4", "php5"] },
  { id: 32, name: "plaintext", extensions: ["txt"] },
  { id: 33, name: "postiats" },
  { id: 34, name: "powerquery" },
  { id: 35, name: "powershell", extensions: ["ps", "ps1"] },
  { id: 36, name: "pug", extensions: ["pug"] },
  { id: 37, name: "python", extensions: ["py", "pyw"] },
  { id: 38, name: "r", extensions: ["r", "rd", "rsx"] },
  { id: 39, name: "razor" },
  { id: 40, name: "redis" },
  { id: 41, name: "redshift" },
  {
    id: 42,
    name: "ruby",
    extensions: [
      "rb",
      "rbx",
      "rjs",
      "gemspec",
      "rake",
      "rb",
      "ru",
      "gemspec",
      "ruby",
    ],
  },
  { id: 43, name: "rust", extensions: ["rs"] },
  { id: 44, name: "sb" },
  {
    id: 45,
    name: "scheme",
    extensions: ["scm", "sld", "sls", "sps", "ss"],
  },
  { id: 46, name: "scss", extensions: ["scss"] },
  { id: 47, name: "shell", extensions: ["sh", "bash", "csh", "ksh", "zsh"] },
  { id: 48, name: "sol", extensions: ["sol"] },
  { id: 49, name: "sql", extensions: ["sql"] },
  { id: 50, name: "st" },
  { id: 51, name: "swift", icon: SwiftIcon, extensions: ["swift"] },
  { id: 52, name: "tcl", extensions: ["tcl", "adp", "tm"] },
  {
    id: 53,
    name: "typescript",
    icon: TypeScriptIcon,
    extensions: ["ts", "tsx"],
  },
  {
    id: 54,
    name: "vb",
    extensions: ["vb", "cls", "vba", "vbhtml", "vbs"],
  },
  { id: 55, name: "xml", extensions: ["xml", "xsl", "xsd", "svg"] },
  { id: 56, name: "yaml", extensions: ["yaml", "yml"] },
];
