import fetch from "node-fetch";
import { Documents } from "../models/Documents";
import { Users } from "../models/Users";

export const createGist = async (
  _id: string,
  code: string,
  URL: string
): Promise<void> => {
  const user = await Users.findOne({ _id });
  if (!user) return;

  const createGist = await fetch("https://api.github.com/gists", {
    method: "POST",
    body: JSON.stringify({
      description: `IMPERIAL Document ${URL} made by ${user.name}. Automatically generated by IMPERIAL`,
      public: false,
      files: {
        "IMPERIAL Document": {
          content: code,
        },
      },
    }),
    headers: {
      authorization: `bearer ${user.githubAccess}`,
    },
  });
  const readableGist = await createGist.json();
  await Documents.updateOne({ URL }, { $set: { gist: readableGist.id } });
};
