type SupportedLanguages = (typeof supportedLanguages)[number]["name"];
type SupportedLanguagesID = (typeof supportedLanguages)[number]["id"];

const supportedLanguages = [
  {
    name: "Auto",
    id: "auto",
  },
  {
    name: "TypeScript",
    id: "typescript",
  },
  {
    name: "JavaScript",
    id: "javascript",
  },
  { name: "Python", id: "python" },
  { name: "Go", id: "go" },
  { name: "C", id: "c" },
  { name: "C++", id: "cpp" },
  { name: "C#", id: "csharp" },
  { name: "HTML", id: "html" },
  { name: "CSS", id: "css" },
  {
    name: "CoffeeScript",
    id: "coffeescript",
  },
  { name: "Java", id: "java" },
  { name: "Rust", id: "rust" },
  { name: "swift", id: "swift" },
  { name: "Kotlin", id: "kotlin" },
  { name: "Clojure", id: "clojure" },
  { name: "Dockerfile", id: "dockerfile" },
  { name: "F#", id: "fsharp" },
  { name: "Graphql", id: "graphql" },
  {
    name: "Handlebars",
    id: "handlebars",
  },
  { name: "Less", id: "less" },
  { name: "Lua", id: "lua" },
  { name: "MySQL", id: "mysql" },
  {
    name: "Objective-c",
    id: "objective-c",
  },
  { name: "Perl", id: "perl" },
  { name: "PHP", id: "php" },
  { name: "R", id: "r" },
  { name: "Redis", id: "redis" },
  { name: "Ruby", id: "ruby" },
  { name: "Apex", id: "apex" },
  { name: "Azcli", id: "azcli" },
  { name: "Bat", id: "bat" },
  { name: "Csp", id: "csp" },
  { name: "INI", id: "ini" },
  { name: "JSON", id: "json" },
  { name: "Markdown", id: "markdown" },
  { name: "Msdax", id: "msdax" },
  { name: "Pascal", id: "pascal" },
  { name: "PGSQL", id: "pgsql" },
  { name: "Plaintext", id: "plaintext" },
  { name: "Postiats", id: "postiats" },
  { name: "Powerquery", id: "powerquery" },
  { name: "Powershell", id: "powershell" },
  { name: "Pug", id: "pug" },
  { name: "Razor", id: "razor" },
  { name: "Redshift", id: "redshift" },
  { name: "SB", id: "sb" },
  { name: "Scheme", id: "scheme" },
  { name: "SCSS", id: "scss" },
  { name: "Shell", id: "shell" },
  { name: "SOL", id: "sol" },
  { name: "SQL", id: "sql" },
  { name: "St", id: "st" },
  { name: "TCL", id: "tcl" },
  { name: "VB", id: "vb" },
  { name: "XML", id: "xml" },
  { name: "YAML", id: "yaml" },
] as const;

export { supportedLanguages };
export type { SupportedLanguages, SupportedLanguagesID };
