import { SupportedLanguagesID } from "@imperial/commons";
import {
  C as CIcon,
  Clojure as ClojureIcon,
  CoffeeScript as CoffeeScriptIcon,
  CPP as CPPIcon,
  CSharp as CSharpIcon,
  CSS as CSSIcon,
  Docker as DockerIcon,
  FSharp as FSharpIcon,
  Go as GoIcon,
  GraphQL as GraphQLIcon,
  Handlebars as HandlebarsIcon,
  HTML as HTMLIcon,
  Java as JavaIcon,
  JavaScript as JavaScriptIcon,
  Kotlin as KotlinIcon,
  Less as LessIcon,
  Lua as LuaIcon,
  MySQL as MySQLIcon,
  ObjectiveC as ObjectiveCIcon,
  Perl as PerlIcon,
  PHP as PHPIcon,
  Python as PythonIcon,
  R as RIcon,
  Redis as RedisIcon,
  Ruby as RubyIcon,
  Rust as RustIcon,
  Swift as SwiftIcon,
  TypeScript as TypeScriptIcon,
} from "../components/Icons";

const languageIcons: Record<SupportedLanguagesID, typeof TypeScriptIcon | undefined> = {
  auto: undefined,
  typescript: TypeScriptIcon,
  javascript: JavaScriptIcon,
  python: PythonIcon,
  go: GoIcon,
  c: CIcon,
  cpp: CPPIcon,
  csharp: CSharpIcon,
  html: HTMLIcon,
  css: CSSIcon,
  coffeescript: CoffeeScriptIcon,
  clojure: ClojureIcon,
  fsharp: FSharpIcon,
  graphql: GraphQLIcon,
  handlebars: HandlebarsIcon,
  java: JavaIcon,
  kotlin: KotlinIcon,
  less: LessIcon,
  lua: LuaIcon,
  mysql: MySQLIcon,
  perl: PerlIcon,
  php: PHPIcon,
  r: RIcon,
  redis: RedisIcon,
  ruby: RubyIcon,
  rust: RustIcon,
  swift: SwiftIcon,
  "objective-c": ObjectiveCIcon,
  dockerfile: DockerIcon,
  apex: undefined,
  azcli: undefined,
  bat: undefined,
  csp: undefined,
  ini: undefined,
  json: undefined,
  markdown: undefined,
  msdax: undefined,
  pascal: undefined,
  pgsql: undefined,
  plaintext: undefined,
  postiats: undefined,
  powerquery: undefined,
  powershell: undefined,
  pug: undefined,
  razor: undefined,
  redshift: undefined,
  sb: undefined,
  scheme: undefined,
  scss: undefined,
  shell: undefined,
  sol: undefined,
  sql: undefined,
  st: undefined,
  tcl: undefined,
  vb: undefined,
  xml: undefined,
  yaml: undefined,
};

function LanguageIcon({ language }: { language: SupportedLanguagesID }) {
  const Icon = languageIcons[language] ?? null;

  return Icon ? <Icon /> : null;
}

export { LanguageIcon };
