on: push
name: lint

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install deps
        run: npm i

      - name: Run ESLint
        run: npm run lint
        env:
          CI: true
