name: push

on:
  push:
    branches: [ next ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
    - name: Copy
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.API_TOKEN_GITHUB }}
        src_path: /services/node/app
        dst_path: /
        dst_owner: Looskie
        dst_repo_name: imperial-build
