name: sentry

on:
  push:
    branches: [ next-next ]
    paths:
      - "services/go/**"

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
    - uses: actions/checkout@v2
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      with:
        environment: staging