name: Test API
on:
  push:
    branches: [next-next]
    paths:
      - apps/api/**

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:18-alpine

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: imperial
          POSTGRES_USER: imperial
          POSTGRES_DB: postgres
          POSTGRES_HOST: localhost
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis
        env:
          REDIS_HOST: localhost
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests
        run: cd ./apps/api && yarn install --immutable && yarn test
